---

environment: qa #Choose the test environment

environments:
 dev:
  base_url:
 qa:
  base_url: https://jsonplaceholder.typicode.com/ #Replace with proper URL
 uat:
  base_url:

settings:
 timeout: 30
 verify_ssl: true
 retries: 2
 header:
  Content-Type: application/json

authentication:
 type: bearer
 token: ""
 username: ""
 password: ""

...